name:                MakeTree
version:             0.1.0.0
github:              "SleepyyPlayz/MakeTree"
license:             GPL-3.0
author:              "Chris Jiang"
maintainer:          "Chris Jiang (please only contact through GitHub)"
copyright:           "2024 Chris Jiang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SleepyyPlayz/MakeTree#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3.8.5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  make-tree:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MakeTree

tests:
  make-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MakeTree
